import Head from "next/head";
/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { supabase } from "./api/supabase";
import { Navigation } from "swiper";
import { Grid, Button, Box } from "@mui/material";
import Backdrop from "@mui/material/Backdrop";
import { FIRST_PATH } from "../constants/Constant";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/grid";
import "swiper/css/pagination";
import { Swiper, SwiperSlide } from "swiper/react";
import Typography from "@mui/material/Typography";
import { PatientStoriesData } from "../constants/Constant";
import { useEffect, useState } from "react";

export const getServerSideProps = async () => {
  const res = await supabase
    .from("blog")
    .select()
    .order("id", { ascending: false });

  console.log("res", res.data);
  const blogs = res.data;

  return { props: { blogs } };
};

export default function Home({ blogs }) {
  const [open, setOpen] = useState(true);
  const [aboutData, setAboutData] = useState();

  useEffect(() => {
    getAboutData();
    setTimeout(() => {
      setOpen(false);
    }, 500);
  }, []);

  const getAboutData = () => {
    supabase
      .from("authentication")
      .select()
      .eq("email", "drharis@test.com")
      .single()
      .then((response) => {
        console.log("response", response?.data);
        setAboutData(response?.data?.items);
      });
  };

  return (
    <Grid>
      <Head>
        <title>Medical Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Backdrop
        sx={{
          color: "#89C1CB",
          backgroundColor: "#89C1CB",
          zIndex: (theme) => theme.zIndex.drawer + 1,
        }}
        open={open}
      >
        <Grid>
          <img
            width={"100%"}
            height={100}
            alt={"Image"}
            src={"/assets/icon/applogo.png"}
          ></img>
        </Grid>
      </Backdrop>
      <Grid>
        <Swiper navigation={true} modules={[Navigation]} slidesPerView={1}>
          {aboutData?.map((x) => {
            return (
              <SwiperSlide key={x}>
                <Link href={x?.url}>
                  <img
                    src={`${FIRST_PATH}${x?.value}`}
                    alt="iamge"
                    width={"100%"}
                    style={{
                      maxHeight: 600,
                    }}
                  />
                </Link>
              </SwiperSlide>
            );
          })}
        </Swiper>
      </Grid>
      <Grid mt={10} mb={2}>
        <Swiper navigation={true} modules={[Navigation]} slidesPerView={1}>
          {blogs?.map((x) => {
            const textDescription = x?.items.find((x) => x?.type === "text");
            return (
              <Grid
                key={x}
                container
                display={"flex"}
                direction={"row"}
                px={{ xs: 2, sm: 5, md: 10, lg: 20 }}
                mb={4}
              >
                <Grid item xs={12} sm={6} pb={4}>
                  <img
                    loading="lazy"
                    src={`${FIRST_PATH}${x?.headerFile}`}
                    alt="iamge"
                    width={"100%"}
                  ></img>
                </Grid>
                <Grid item xs={12} sm={6} px={{ sm: 6, md: 10 }} pt={{ md: 5 }}>
                  <Typography variant="h5" color={"#333333"}>
                    {x?.title}
                  </Typography>

                  <Typography variant="body1" color={"#333333"} mt={6}>
                    {textDescription?.value.length > 100
                      ? textDescription?.value.slice(0, 100) + "..."
                      : textDescription?.value}
                  </Typography>
                  <Link href={`blog/blog-detail/${x?.id}`}>
                    <Button
                      sx={{
                        mt: 4,
                        borderRadius: 0,
                        backgroundColor: "#AFB5B9",
                        color: "white",

                        ":hover": {
                          backgroundColor: "#89C1CB",
                        },
                      }}
                      variant="contained"
                    >
                      read more
                    </Button>
                  </Link>
                </Grid>
              </Grid>
            );
          })}
        </Swiper>
      </Grid>
    </Grid>
  );
}
