import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { Navigation } from "swiper";
import { Grid } from "@mui/material";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/grid";
import "swiper/css/pagination";
import { Swiper, SwiperSlide } from "swiper/react";
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import { CardActionArea } from "@mui/material";
import CardMedia from "@mui/material/CardMedia";
import Typography from "@mui/material/Typography";
import { homeData } from "../constants/Constant";

export default function Home() {
  console.log("h", homeData);
  return (
    <Grid>
      <Head>
        <title>Medical Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid>
        <Swiper navigation={true} modules={[Navigation]} slidesPerView={1}>
          {homeData?.map((x) => {
            return (
              <SwiperSlide key={x}>
                {/* <Card sx={{ width: 200 }}>
                <CardActionArea> */}
                <img src={x?.url} alt="Girl in a jacket" width="100%" />
                {/* <Typography
                      sx={{
                        fontSize: 13,
                        textAlign: "center",
                        color: "White",
                      }}
                    >
                      {x?.text}
                    </Typography> */}
                {/* </CardActionArea>
              </Card> */}
              </SwiperSlide>
            );
          })}
        </Swiper>
      </Grid>

      <Grid
        container
        // display={"flex"}
        direction={"row"}
        spacing={3}
        pt={3}
      >
        <Grid item xs={12} sm={6}>
          <Link href="https://www.ektorgrammatopoulos.com/orthodontics-treatment-for-adult/">
            <img
              loading="lazy"
              src="https://www.ektorgrammatopoulos.com/wp-content/uploads/2018/12/detier-thumb1-e1549990722296.jpg"
              alt="image"
              width={"100%"}
            />

            <h3>For Adults</h3>
          </Link>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Link href="https://www.ektorgrammatopoulos.com/orthodontics-treatment-for-children/">
            <img
              loading="lazy"
              src="https://www.ektorgrammatopoulos.com/wp-content/uploads/2018/12/detier-thumb2-e1549990637829.jpg"
              alt="image"
              width={"100%"}
            />

            <h3> For Children</h3>
          </Link>
        </Grid>
      </Grid>
    </Grid>
  );
}
