import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { Grid, Navigation } from "swiper";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/grid";
import "swiper/css/pagination";
import { Swiper, SwiperSlide } from "swiper/react";
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import { CardActionArea } from "@mui/material";
import CardMedia from "@mui/material/CardMedia";
import Typography from "@mui/material/Typography";
import { HomeData } from "../constants/Constant";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Medical Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Swiper navigation={true} modules={[Navigation]} slidesPerView={4}>
        {HomeData?.map((x) => {
          <SwiperSlide>
            <Card sx={{ width: 200 }}>
              <CardActionArea>
                <CardContent sx={{ backgroundColor: "#2E2F2F" }}>
                  <img
                    src={x?.url}
                    alt="Girl in a jacket"
                    width="400"
                    height="300"
                  />
                  <Typography
                    sx={{
                      fontSize: 10,
                      textAlign: "center",
                      color: "White",
                      fontWeight: "bold",
                    }}
                  >
                    {x?.text}
                  </Typography>
                </CardContent>
              </CardActionArea>
            </Card>
          </SwiperSlide>;
        })}
      </Swiper>

      <Link href="https://www.ektorgrammatopoulos.com/orthodontics-treatment-for-adult/">
        <img
          loading="lazy"
          src="https://www.ektorgrammatopoulos.com/wp-content/uploads/2018/12/detier-thumb1-e1549990722296.jpg"
          alt="image"
        />

        <h3>For Adults</h3>
      </Link>

      <Link href="https://www.ektorgrammatopoulos.com/orthodontics-treatment-for-children/">
        <img
          loading="lazy"
          src="https://www.ektorgrammatopoulos.com/wp-content/uploads/2018/12/detier-thumb2-e1549990637829.jpg"
          alt="image"
        />

        <h3> For Children</h3>
      </Link>
    </div>
  );
}
